sudo: required
language: node_js

services:
  - docker


before_script:
  - cd application && docker build -t sapfir0/web-premier-eye:server .
  - cd ../SPA && docker build -t sapfir0/web-premier-eye:client .

#script:
#  - docker run -p 8050:8050 sapfir0/web-premier-eye:server
#  - docker run -p 5000:80 sapfir0/web-premier-eye:client


after_success:
  - docker login --username $DOCKER_USER --password $DOCKER_PASS
  - docker push sapfir0/web-premier-eye:client
  - docker push sapfir0/web-premier-eye:server



