version: '3'
services:
  server:
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: DockerfileServer
    ports:
      - "8050:8050"

  client:
    restart: always
    build:
      context: .
      dockerfile: DockerfileClient
    ports:
      - "8080:8080"


