version: '3'
services:
  server:
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: application/Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - "./application/static/uploads:/pyfront/application/static/uploads"
      - "./data.db:/pyfront/data.db"
    networks:
      - some-net

  client:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    stdin_open: true

networks:
  some-net:
    driver: bridge