version: '3'
services:
  server:
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: DockerfileServer
    ports:
      - "8050:8050"
    volumes:
      - "./application/static/uploads:/pyfront/application/static/uploads"
    networks:
      - some-net

  client:
    restart: always
    build:
      context: .
      dockerfile: DockerfileClient
    ports:
      - "8080:80"

networks:
  some-net:
    driver: bridge