version: '3'
services:
  server:
    restart: always
    build: ./server
    ports:
      - "5000:5000"

  client:
    restart: always
    env_file: .env
    build: ./
    ports:
      - "8080:8080"


